### ISSUE TITLE
Local Docker Builds

### ISSUE THREAD

**Issue by thedwillis** [cwoolum/ThinNugetProxy#1]
Currently this client works great when performing the entire build process in Azure pipelines, however when performing local docker builds using the same DockerFile the builds fail due to a reliance on an Azure pipelines host address, i.e. http://172.17.0.1:8080/v3/index.json.

Is there a solution as simple as this proxy that allows for local builds? I've seen your article on https://medium.com/@cwoolum/using-nuget-restore-securely-inside-of-docker-containers-with-caching-2c2f5453905d which appears to have better support for both local and Azure builds, but I was hoping there was something more streamlined like this.

**Comment by cwoolum** [comment]
You bring up a good point!  This process should run the same locally but you'll need to create the proxy container yourself.

`docker run -e "MIRROR__PACKAGESOURCE=https://pkgs.dev.azure.com/my-nuget-server/_packaging/Nuget/nuget/v3/index.json" -e "MIRROR__ACCESSTOKEN={a_PAT_you_have_created}" -p 8080:80 cwoolum/thin-nuget-proxy`

If you add the `-d` flag, it'll run in detached mode and just continue operating in the background. I just tested this in Docker for Windows with no issues.

Does this work for you?

**Comment by thedwillis** [comment]
That's great! Thanks very much
